'use client';
import ParentComponent from '@/components/ParentComponent';
import '@/styles/globals.css';
import { useState } from 'react';

const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  const [asideOpen, setAsideOpen] = useState(false);
  const AsideClickOpen = () => {
    setAsideOpen(!asideOpen);
  };
  return (
    <>
      <html lang="en">
        <body>
          <ParentComponent appOpen={asideOpen} appAsideOpen={AsideClickOpen} />
          <main>
            <div className={asideOpen ? 'container' : 'container active'}>
              {children}
            </div>
          </main>
        </body>
      </html>
    </>
  );
}
