import Header from '@/components/Header';
import ParentComponent from '@/components/ParentComponent';
import '@/styles/globals.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <>
      <html lang="en">
        <h1>Site is live</h1>
        <body>
          <ParentComponent />
          {children}
        </body>
      </html>
    </>
  );
}
